# Generated by Django 2.2.7 on 2019-12-18 12:37

import blogpage.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_page',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='genre',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('fiction', 'Fiction'), ('culinary', 'Culinary'), ('non-fiction', 'Non-Fiction'), ('technology', 'Technology')], max_length=20, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified On'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=blogpage.models.upload_image, verbose_name='Image'),
        ),
    ]
