# Generated by Django 2.2.7 on 2019-12-24 07:24

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blogpage', '0002_auto_20191218_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_page',
            name='keyword',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='blog_page',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified On'),
        ),
    ]
