# Generated by Django 2.2.7 on 2020-01-02 07:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_auto_20191224_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_page',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
