# Generated by Django 2.2.7 on 2020-01-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0004_auto_20200102_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_page',
            name='content',
        ),
        migrations.AlterField(
            model_name='blog_page',
            name='genre',
            field=models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Biography', 'Biography'), ('Culinary', 'Culinary'), ('Fiction', 'Fiction'), ('Mythology', 'Mythology'), ('Non-Fiction', 'Non-Fiction'), ('Technology', 'Technology')], max_length=20, null=True, verbose_name='Genre'),
        ),
    ]
